### ISSUE TITLE
Error in print statement 

### ISSUE THREAD

**Issue by Joynctu** [NanoNets/TF-OD-Pi-Test#1]
python ObjectDetectionPredict.py --model data/0/quantized_graph.pb --labels data/label_map.pbtxt --images data/image1.jpg data/image2.jpg 

gives the output 

Traceback (most recent call last):
  File "ObjectDetectionPredict.py", line 97, in <module>
    main()
  File "ObjectDetectionPredict.py", line 91, in main
    print("\n".join("{0:<20s}: {1:.1f}%".format(ObjectDetectionPredict_class.category_index[c]['name'], s*100.) for (c, s) in zip(classes[0], scores[0])))
  File "ObjectDetectionPredict.py", line 91, in <genexpr>
    print("\n".join("{0:<20s}: {1:.1f}%".format(ObjectDetectionPredict_class.category_index[c]['name'], s*100.) for (c, s) in zip(classes[0], scores[0])))
KeyError: 53.0

**Comment by prats226** [comment]
Can you paste content of label_map.pbtxt file? Also can you print output of scores, classes, image_with_labels in previous line? Looks like some bug in printing all info.

**Comment by naderafshari** [comment]
I have the same issue. Was this problem resolved?

**Comment by prats226** [comment]
Hi @naderafshari Can you paste content of label_map.pbtxt file? Also can you print output of scores, classes, image_with_labels in previous line? Looks like some bug in printing all info.

**Comment by naderafshari** [comment]
thank you for respoding @NanoNets

label_map.pbtxt has this...
item {
  name: "roll"
  id: 1
}
item {
  name: "sleep"
  id: 2
}
item {
  name: "lay"
  id: 3
}
item {
  name: "stand"
  id: 4
}
scores...
[[0.5288982  0.08372335 0.04201065 0.00606666 0.00589032 0.00416868
  0.00392445 0.00318479 0.00312263 0.00260904 0.00251406 0.00237433
  0.00231907 0.00222939 0.00220274 0.00219575 0.0021678  0.00213818
  0.00211585 0.00209311 0.00208792 0.00206721 0.00205824 0.00201472
  0.00199873 0.00197131 0.00195797 0.00195733 0.00193307 0.001916
  0.00191302 0.00190766 0.00190628 0.00188895 0.00186853 0.00186825
  0.00186308 0.00186014 0.00185487 0.00185377 0.00185061 0.00183157
  0.00183052 0.00182039 0.001819   0.00181721 0.00181386 0.00180681
  0.00180577 0.00180501 0.00180498 0.00180134 0.00180007 0.0017896
  0.00178943 0.0017893  0.00178413 0.00177893 0.00177829 0.0017765
  0.00176905 0.0017622  0.0017554  0.00175419 0.00174482 0.00174374
  0.00172688 0.00172355 0.00171909 0.00171479 0.001714   0.00170866
  0.00170865 0.00170737 0.00170587 0.00170491 0.00170338 0.00170087
  0.00169897 0.0016975  0.00169351 0.00169331 0.00168201 0.00168198
  0.00168137 0.00167958 0.00167751 0.00167547 0.00167466 0.00167309
  0.00166824 0.00166803 0.00166747 0.00166024 0.00165972 0.00165314
  0.00165282 0.0016502  0.00164872 0.00164702]]
classes...
[[ 2.  4.  2.  2.  2.  1.  1.  1.  3. 63. 31. 63. 35.  3. 27.  2. 31. 78.
  66. 83. 11. 44. 61.  3. 78. 88. 80. 35. 72. 36. 55. 61. 44. 54.  8. 51.
  88. 83. 68. 76. 16. 73.  1.  3. 80. 22. 29. 70. 76. 17. 58. 21. 72. 22.
  17.  6. 27. 82.  5. 57. 55. 87. 54. 29. 33.  5. 67. 31. 45. 40. 72. 70.
  48. 11.  6. 34. 45. 61. 11. 53. 23. 78. 16. 18. 81. 57. 39. 85. 72. 14.
  72. 88. 14. 23. 70. 25. 69. 50.  6. 85.]]

image_with_labels...
[[[243 243 251]
  [243 243 251]
  [243 243 251]
  ...
  [228 238 250]
  [228 238 250]
  [228 238 250]]

 [[243 243 251]
  [243 243 251]
  [243 243 251]
  ...
  [228 238 250]
  [228 238 250]
  [228 238 250]]

 [[243 243 251]
  [243 243 251]
  [243 243 251]
  ...
  [228 238 250]
  [228 238 250]
  [228 238 250]]

 ...

 [[176 173  92]
  [178 176  91]
  [204 203 110]
  ...
  [189 196  92]
  [189 196  90]
  [189 196  90]]

 [[180 177  96]
  [164 162  77]
  [163 162  69]
  ...
  [185 192  89]
  [185 192  86]
  [185 192  88]]

 [[195 192 113]
  [189 187 104]
  [180 179  86]
  ...
  [183 189  89]
  [183 190  86]
  [184 191  88]]]

**Comment by naderafshari** [comment]
problem seem to be in here
ObjectDetectionPredict_class.category_index[c]['name']
when replace it with a constant string, it prints out

**Comment by naderafshari** [comment]
ObjectDetectionPredict_class.category_index contains...
{1: {'id': 1, 'name': u'roll'}, 2: {'id': 2, 'name': u'sleep'}, 3: {'id': 3, 'name': u'lay'}, 4: {'id': 4, 'name': u'stand'}}
I don't know if the character u in the name attributes are normal

**Comment by naderafshari** [comment]
Sorry for my ignorance but why there are 100 entries in classes[0] and scores[0] where there are only 4 classes in my case?  Also, I've noticed on a RPI3B+ a single image classification takes about 30secs. Is that normal? Is there way to speed it up?
